### PR TITLE
fix all warnings

### PR DESCRIPTION
**Pull request by yoshuawuyts**
- ran cargo test
- ran cargo fmt

Thanks!

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@spacekookie it works better with the 80 character limit that's also included. Especially on smaller devices (laptops, tablets, phones), and split-screen setups it becomes easier to work with for a wider number of people.

**Comment by spacekookie** [comment]
If that's the code style you want to enforce for the project, maybe also include a `rustfmt.toml` so people's auto-format macros don't mess up the code needlessly later :grimacing: :+1:

**Comment by killercup** [comment]
@spacekookie the repo already has a rustfmt.toml file :)

> it works better with the 80 character limit that's also included. Especially on smaller devices (laptops, tablets, phones), and split-screen setups

@yoshuawuyts good arguments, but I stand by my choice to instead use [Iosevka](https://be5invis.github.io/Iosevka/) everywhere

**Comment by yoshuawuyts** [comment]
@spacekookie https://github.com/rust-clique/man/blob/master/rustfmt.toml :tada:

**Pull request merged**
